apply plugin: "java"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
sourceSets.main.java.srcDirs = [ "src/" ]

project.ext.mainClassName = "io.anuke.novix.desktop.DesktopLauncher"
project.ext.assetsDir = new File("../core/assets");

tasks.register('run', JavaExec) {
    dependsOn classes
    mainClass = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath + files(project.assetsDir)
    standardInput = System.in
    workingDir = project.projectDir
    ignoreExitValue = true
}

tasks.register('debug', JavaExec) {
    dependsOn classes
    mainClass = project.mainClassName
    classpath = sourceSets.main.runtimeClasspath + files(project.assetsDir)
    standardInput = System.in
    workingDir = project.projectDir
    ignoreExitValue = true
    debug = true
}

tasks.register('dist', Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from files(sourceSets.main.output.classesDirs)
    from files(sourceSets.main.output.resourcesDir)
    from { configurations.runtimeClasspath.collect { zipTree(it) } }
    from files(project.assetsDir);

    manifest {
        attributes 'Main-Class': project.mainClassName
    }
}

dist.dependsOn classes
